import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Haeder from "@/components/Haeder/Haeder";
import Footer from "@/components/Footer/Footer";
import TelegramWebAppInit from "@/components/TelegramWebAppInit/TelegramWebAppInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <TelegramWebAppInit />
        <Haeder />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
